In [1]:
from sklearn.svm import SVC
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import classification_report
from sklearn.inspection import permutation_importance
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report,precision_recall_fscore_support

In [2]:
mental_df = pd.read_csv('new_output.csv')


In [3]:
# Define the target set.
y = mental_df["If yes, what condition(s) have you been diagnosed with?"]
# Define the features set.
X = mental_df[["Are you self-employed?",
"Do you work remotely?",
"Have you had a mental health disorder in the past?",
"Do you believe your productivity is ever affected by a mental health issue?",
"Do you have a family history of mental illness?",
"do you feel comfortable in your working environment?",
"do  you feel comfortable working  with your direct supervisor(s)?",
"Do you feel that your organisation takes mental health as seriously as physical health?",
"Have you observed or experienced an unsupportive or badly handled response to an issue in your current workplace?",
"are you stressed about your career?",
"Have you ever sought treatment for a mental health issue from a mental health professional?",
"How willing would you be to share with friends and family about your work stress?",
"Do you currently have a mental health disorder?",
"Have you observed or experienced an unsupportive or badly handled response to an issue in your current workplace?",
"Did you feel that your previous employers took mental health as seriously as physical health?",
"Have your previous employers provided mental health benefits?"]]

In [4]:
# Splitting into Train and Test sets.
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [5]:
# feature names
feature_names = list(X_train.columns)


In [6]:
svm_classifier = SVC(kernel='rbf', decision_function_shape='ovr')

In [7]:
# Train the SVM classifier
svm_classifier.fit(X_train, y_train)


SVC()

In [8]:
# Predict on the test set
y_pred = svm_classifier.predict(X_test)

In [9]:
# Evaluate the classifier
accuracy = accuracy_score(y_test, y_pred)
classification_report = classification_report(y_test, y_pred)

c:\Python310\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Python310\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Python310\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [10]:
# Making predictions using the testing data.
predictions = svm_classifier.predict(X_test)
predictions

array(['Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)',
       ...,
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Eating Disorder (Anorexia, Bulimia, etc)|Obsessive-Compulsive Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Eating Disorder (Anorexia, Bulimia, etc)'],
      dtype=object)

In [11]:
# Calculating the accuracy score.
acc_score = accuracy_score(y_test, predictions)

In [12]:
prec=precision_recall_fscore_support(y_test,predictions)

c:\Python310\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [15]:
# Calculate confusion matrix
cm = confusion_matrix(y_test, y_pred)
print('Confusion Matrix:')
print(cm)

# Calculate precision, recall, f1-score, support
precision, recall, f1_score, support = precision_recall_fscore_support(y_test, y_pred)
print('Precision:', precision)
print('Recall:', recall)
print('F1-score:', f1_score)
print('Support:', support)

Confusion Matrix:
[[  2   0   0 ...   0   0   0]
 [  0 348   0 ...   0   0   0]
 [  0   0   7 ...   0   0   0]
 ...
 [  0   0   0 ...   7   0   0]
 [  0   0   0 ...   0  10   0]
 [  0   0   0 ...   0   0   5]]
Precision: [1.         0.80930233 1.         0.72321429 1.         0.62857143
 1.         1.         0.         0.46666667 0.96348487 1.
 0.83823529 0.         0.72727273 0.         1.         1.
 1.         1.         1.         1.         1.         1.
 1.         1.         1.         1.         1.         1.
 0.         1.         0.36363636 1.         1.         1.
 0.79069767 1.         1.         1.         1.         1.
 1.         1.         0.         1.         1.         0.62962963
 0.         1.         0.65217391 0.53333333 1.         0.72093023
 1.         1.         1.         1.         1.         1.
 1.         1.         1.         1.         0.         1.
 1.         1.         1.         1.         1.         1.
 1.         1.         0.         0.         1.

c:\Python310\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [16]:
import pickle

# Define the file name for the pickled model
pkl_filename = "svm_pickle_model.pkl"

# Create a dictionary object containing the model and feature names
model_dict = {"model": svm_classifier, "feature_names": feature_names}

# Pickle the dictionary object to the file
with open(pkl_filename, 'wb') as file:
    pickle.dump(model_dict, file)

# Load the pickled model from file
with open(pkl_filename, 'rb') as file:
    pickled_model = pickle.load(file)

# Retrieve the SVM model and feature names from the dictionary object
svm_model = pickled_model["model"]
loaded_feature_names = pickled_model["feature_names"]
